security:
  ignored: /css/**,/js/**,/favicon.ico,/webjars/**,/images/**,/static/**,/hystrix.stream/**,/info,/error,/actuator/**,/env,/metrics,/trace,/dump,/jolokia,/configprops,/activiti,/logfile,/refresh,/flyway,/liquibase,/loggers,/druid/**,/oauth/deleteToken, /backReferer,/guoqing/test
server:
  port: 18001
spring:
  redis:
    database: 0
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/main-data?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: "root"
    driver-class-name: com.mysql.jdbc.Driver
  freemarker:
      request-context-attribute: request
  rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: 'guest'
logging:
  file: logs/auth-center.log
wx:
  miniprogram:
    appid: wxc2c5d67ce3747ff1
    appsecret: 74e54f145a3b01b44ef15f05e27117dd
guoqing:
  test: yuheng3
management:
  endpoints:
    web:
      exposure:
        include: refresh
