server:
  port: 18002
# 数据源配置
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/main-data?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: "root"
    driver-class-name: com.mysql.jdbc.Driver
  redis:
      database: 0
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: 'guest'
# 权限配置
security:
  ignored: /css/**,/js/**,/favicon.ico,/webjars/**,/images/**,/hystrix.stream/**,/info,/error,/actuator/**,/env,/metrics,/trace,/dump,/jolokia,/configprops,/activiti,/logfile,/refresh,/flyway,/liquibase,/loggers,/user/phone/**,/role/user/**,/menu/user/*,/client/all,/guoqing/test
  oauth2:
    resource:
      jwt:
        key-uri: http://${AUTH_CENTER_HOST:localhost}:${AUTH_CENTER_PORT:18001}/auth/oauth/token_key
      id: ${spring.application.name}
      serviceId: ${spring.application.name}
logging:
  file: logs/main-data.log
guoqing:
  test: heheda3
management:
  endpoints:
    web:
      exposure:
        include: refresh
